/**
 * Persistence and bounded retention for MCP browser screenshots.
 *
 * Production files live only under `<os.tmpdir()>/agent-deck-browser/<session>/`. The store never
 * follows a symlink at the managed root, session-directory, or screenshot-file level, and the
 * reaper only recognizes filenames generated by this module (including the pre-retention format).
 */

import { randomUUID } from 'node:crypto';
import { promises as fsp } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve, sep } from 'node:path';

export const BROWSER_SCREENSHOT_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;
export const BROWSER_SCREENSHOT_REAP_INTERVAL_MS = 24 * 60 * 60 * 1000;

const GENERATED_SCREENSHOT_NAME =
  /^tab-[1-9]\d*-\d+(?:-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?\.png$/;
const SAFE_SESSION_SEGMENT = /^[a-zA-Z0-9._-]{1,80}$/;

interface BrowserScreenshotStoreDeps {
  rootDir: string;
  now?: () => number;
  id?: () => string;
}

export class BrowserScreenshotStore {
  private readonly rootDir: string;
  private readonly now: () => number;
  private readonly id: () => string;
  private lastReapAttemptAt: number | null = null;
  private activeReap: Promise<number> | null = null;

  constructor(deps: BrowserScreenshotStoreDeps) {
    this.rootDir = resolve(deps.rootDir);
    this.now = deps.now ?? Date.now;
    this.id = deps.id ?? randomUUID;
  }

  async persist(sessionId: string, tabId: number, png: Buffer): Promise<string> {
    if (!Number.isInteger(tabId) || tabId <= 0) {
      throw new Error(`Invalid browser tab id for screenshot: ${tabId}.`);
    }
    if (png.byteLength === 0) throw new Error('Cannot persist an empty browser screenshot.');

    const rootReal = await this.ensureRoot();
    const sessionSegment = sanitizeSegment(sessionId);
    const sessionDir = join(this.rootDir, sessionSegment);
    await fsp.mkdir(sessionDir, { recursive: true, mode: 0o700 });
    await assertManagedDirectory(sessionDir, rootReal, sessionSegment);

    const filename = `tab-${tabId}-${this.now()}-${this.id()}.png`;
    const path = join(sessionDir, filename);
    await fsp.writeFile(path, png, { flag: 'wx', mode: 0o600 });

    // Best effort and throttled. Persistence succeeds independently of cleanup availability.
    void this.maybeReap();
    return path;
  }

  /** Startup uses the same throttle marker as opportunistic screenshot-triggered cleanup. */
  reapAtStartup(): Promise<number> {
    return this.maybeReap();
  }

  maybeReap(): Promise<number> {
    if (this.activeReap != null) return this.activeReap;
    const now = this.now();
    if (
      this.lastReapAttemptAt != null
      && now - this.lastReapAttemptAt < BROWSER_SCREENSHOT_REAP_INTERVAL_MS
    ) {
      return Promise.resolve(0);
    }

    this.lastReapAttemptAt = now;
    const attempt = this.reap(BROWSER_SCREENSHOT_MAX_AGE_MS, now)
      .catch((error) => {
        void error;
        return 0;
      })
      .finally(() => {
        if (this.activeReap === attempt) this.activeReap = null;
      });
    this.activeReap = attempt;
    return attempt;
  }

  async reap(maxAgeMs = BROWSER_SCREENSHOT_MAX_AGE_MS, now = this.now()): Promise<number> {
    if (!Number.isFinite(maxAgeMs) || maxAgeMs < 0) {
      throw new Error(`Invalid browser screenshot max age: ${maxAgeMs}.`);
    }

    const rootReal = await this.existingRootReal();
    if (rootReal == null) return 0;
    const cutoff = now - maxAgeMs;
    const sessionEntries = await fsp.readdir(this.rootDir, { withFileTypes: true });
    let reaped = 0;

    for (const sessionEntry of sessionEntries) {
      if (!sessionEntry.isDirectory() || !SAFE_SESSION_SEGMENT.test(sessionEntry.name)) continue;
      const sessionDir = join(this.rootDir, sessionEntry.name);
      try {
        await assertManagedDirectory(sessionDir, rootReal, sessionEntry.name);
        const files = await fsp.readdir(sessionDir, { withFileTypes: true });
        for (const file of files) {
          if (!file.isFile() || !GENERATED_SCREENSHOT_NAME.test(file.name)) continue;
          const path = join(sessionDir, file.name);
          try {
            const stat = await fsp.lstat(path);
            if (!stat.isFile() || stat.isSymbolicLink() || stat.mtimeMs >= cutoff) continue;
            await fsp.unlink(path);
            reaped += 1;
          } catch {
            // One raced or unreadable file must not prevent cleanup of the remaining sessions.
          }
        }
      } catch {
        // A replaced, symlinked, or unreadable session directory is outside the managed set.
      }
    }

    return reaped;
  }

  private async ensureRoot(): Promise<string> {
    await fsp.mkdir(this.rootDir, { recursive: true, mode: 0o700 });
    const rootReal = await managedDirectoryReal(this.rootDir);
    const parentReal = await fsp.realpath(dirname(this.rootDir));
    const expectedReal = join(parentReal, basename(this.rootDir));
    if (rootReal !== expectedReal) {
      throw new Error('Browser screenshot root resolves outside its configured location.');
    }
    return rootReal;
  }

  private async existingRootReal(): Promise<string | null> {
    try {
      const rootReal = await managedDirectoryReal(this.rootDir);
      const parentReal = await fsp.realpath(dirname(this.rootDir));
      if (rootReal !== join(parentReal, basename(this.rootDir))) {
        throw new Error('Browser screenshot root resolves outside its configured location.');
      }
      return rootReal;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }
}

async function managedDirectoryReal(path: string): Promise<string> {
  const stat = await fsp.lstat(path);
  if (stat.isSymbolicLink() || !stat.isDirectory()) {
    throw new Error(`Managed browser screenshot path is not a real directory: ${path}`);
  }
  return fsp.realpath(path);
}

async function assertManagedDirectory(
  path: string,
  rootReal: string,
  expectedName: string,
): Promise<void> {
  const real = await managedDirectoryReal(path);
  const prefix = rootReal.endsWith(sep) ? rootReal : rootReal + sep;
  if (real !== join(rootReal, expectedName) || !real.startsWith(prefix)) {
    throw new Error('Browser screenshot session directory resolves outside the managed root.');
  }
}

function sanitizeSegment(value: string): string {
  return value.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 80) || 'session';
}

const browserScreenshotStore = new BrowserScreenshotStore({
  rootDir: join(tmpdir(), 'agent-deck-browser'),
});

export function persistBrowserScreenshot(
  sessionId: string,
  tabId: number,
  png: Buffer,
): Promise<string> {
  return browserScreenshotStore.persist(sessionId, tabId, png);
}

export function reapBrowserScreenshotsAtStartup(): Promise<number> {
  return browserScreenshotStore.reapAtStartup();
}
