import type { AppSettings } from '@shared/types';

export const LOCAL_WORKER_DESKTOP_STATE_PATH =
  '.agent-deck/local-worker-desktop-state.v1';

export const LOCAL_WORKER_SYNCED_PROVIDER_SETTING_KEYS = Object.freeze([
  'bundledAgentRuntimeOverrides',
  'claudeCliPath',
  'claudeCodeSandbox',
  'codexCliPath',
  'codexSandbox',
  'continuationCheckpointAdapter',
  'continuationCheckpointAutoRefreshEnabled',
  'continuationCheckpointAutoRefreshIntervalMinutes',
  'continuationCheckpointMaxConcurrent',
  'continuationCheckpointModel',
  'continuationCheckpointRuntimeProvider',
  'continuationCheckpointThinking',
  'continuationRawRetentionTokens',
  'enableAgentDeckMcp',
  'grokCliPath',
  'grokSandbox',
  'injectAgentDeckClaudeAgents',
  'injectAgentDeckClaudeMd',
  'injectAgentDeckClaudeSkills',
  'injectAgentDeckCodexAgents',
  'injectAgentDeckCodexAgentsMd',
  'injectAgentDeckCodexSkills',
  'injectAgentDeckGrokAgents',
  'injectAgentDeckGrokAgentsMd',
  'injectAgentDeckGrokSkills',
  'mcpHttpEnabled',
  'mcpMaxFanOutPerParent',
  'mcpMaxSpawnDepth',
  'mcpSpawnRatePerMinute',
  'permissionTimeoutMs',
  'summaryAdapter',
  'summaryEnabled',
  'summaryEventCount',
  'summaryIntervalMs',
  'summaryMaxConcurrent',
  'summaryModel',
  'summaryRuntimeProvider',
  'summaryThinking',
] as const satisfies readonly (keyof AppSettings)[]);
