export const REMOTE_HOST_PAGE_LIMIT = 40;
export const REMOTE_HOST_MAX_PAGE_LIMIT = 100;
export const REMOTE_HOST_MAX_HISTORY_LIMIT = 100;
export const REMOTE_HOST_MAX_TEXT_BYTES = 65_536;
export const REMOTE_HOST_MAX_JSON_BYTES = 65_536;
export const REMOTE_HOST_MAX_PENDING_ITEMS = 100;
