import { vi } from 'vitest';

import type { RemoteSessionSourceView } from './source-types';

export function remoteSource(): RemoteSessionSourceView {
  const session = {
    id: 'same-session',
    adapterId: 'codex-cli',
    title: 'Remote session',
    status: 'active-idle',
    createdAt: 1,
    updatedAt: 2,
  };
  return {
    addressableIdentityKey: 'remote-a:core-a:1',
    busy: false,
    capabilities: new Set([
      'events.replay',
      'sessions.write',
      'pending.read',
      'pending.respond',
      'sessions.runtime.read',
      'sessions.runtime.write',
      'sessions.context.read',
      'sessions.input.read',
      'sessions.presentation.read',
    ]),
    dataRevision: 0,
    resourceRevisions: {
      'session-list': 0, 'session-detail': 0, pending: 0,
      issues: 0, usage: 0, 'node-configuration': 0, 'node-assets': 0,
    },
    error: null,
    eventLoadError: null,
    events: {
      events: [{
        id: 1,
        sessionId: session.id,
        agentId: 'codex-cli',
        kind: 'message',
        payload: { role: 'assistant', text: 'remote-only activity' },
        ts: 2,
      }],
      revision: 2,
      truncated: false,
    },
    historyLoadError: null,
    historyLoading: false,
    historyPaginationBusy: false,
    historyArchivedOnly: false,
    historyQuery: '',
    historySessions: [],
    hasMoreHistorySessions: false,
    hasMoreSessions: false,
    identity: 'remote-a:core-a:1',
    loading: false,
    livePaginationBusy: false,
    pendingBuckets: [],
    pendingBySession: new Map(),
    pendingLoading: false,
    pendingPaginationBusy: false,
    pendingLoadError: null,
    pendingTotal: 0,
    pendingScanTruncated: false,
    hasMorePending: false,
    presentationCounts: null,
    profile: {
      id: 'remote-a',
      label: 'Production Core',
      scope: 'remote',
      endpoint: {
        hostname: 'core.example.test',
        port: 22,
        username: 'agentdeck',
        hostKeyFingerprint: 'SHA256:test',
      },
    },
    recoveringWorker: false,
    context: {
      contextUsage: {
        usedTokens: 34_000,
        windowTokens: 100_000,
        updatedAt: 2,
        runtimeIdentity: {
          version: 1,
          runtimeKey: 'codex:openai:remote-model:default',
          adapter: 'codex-cli',
          runtimeProvider: 'openai',
          model: 'remote-model',
          capacityConfigFingerprint: 'default',
        },
      },
      revision: 3,
    },
    runtime: { adapterId: 'codex-cli', values: { model: 'remote-model' }, revision: 3 },
    runtimeLoadError: null,
    contextLoadError: null,
    inputCapabilities: null,
    inputLoadError: null,
    summaryLoadError: null,
    summaries: null,
    taskLoadError: null,
    tasks: null,
    sessionTotal: 1,
    selectedPending: { requests: [], revision: 4 },
    selectedSession: session,
    selectedSessionId: session.id,
    sessions: [{
      id: session.id,
      adapterId: session.adapterId,
      title: session.title,
      source: 'sdk',
      lifecycle: 'active',
      activity: 'idle',
      archived: false,
      pinned: false,
      createdAt: session.createdAt,
      updatedAt: session.updatedAt,
      endedAt: null,
      model: null,
      thinking: null,
      runtimeProvider: null,
      context: null,
      spawnedBy: null,
      spawnDepth: 0,
      teams: [],
      summary: null,
      summaryGenerationSource: null,
      workspaceLabel: null,
      contextOnly: false,
    }],
    state: {
      profileId: 'remote-a',
      status: 'connected',
      recovery: null,
      authoritativeCoreId: 'authoritative-a',
      workerGeneration: null,
      capabilities: [],
      eventRevision: 2,
      error: null,
    },
    usable: true,
    clearError: vi.fn(),
    archiveHistorySession: vi.fn(),
    createSession: vi.fn(),
    createWorkspaceDirectory: vi.fn(),
    deleteHistorySession: vi.fn(),
    getSessionCapabilities: vi.fn(),
    listWorkspaceDirectories: vi.fn(),
    listFileChanges: vi.fn(),
    getFileChange: vi.fn(),
    getFileFinalDiff: vi.fn(),
    loadImageBlob: vi.fn(async () => ({ ok: false as const, reason: 'unsupported_source' as const })),
    planReviewTransport: vi.fn(() => null),
    interrupt: vi.fn(),
    previewHandOff: vi.fn(),
    commitHandOff: vi.fn(),
    loadMoreHistorySessions: vi.fn(),
    listOutgoing: vi.fn(async () => ({
      sessionId: 'remote-session', adapterId: 'codex-cli', messages: [], revision: 1,
    })),
    loadMorePending: vi.fn(),
    loadMoreSessions: vi.fn(),
    refresh: vi.fn(),
    respondPending: vi.fn(),
    removeOutgoing: vi.fn(async () => true),
    selectSession: vi.fn(),
    setHistoryQuery: vi.fn(),
    setHistoryArchivedOnly: vi.fn(),
    send: vi.fn(),
    steer: vi.fn(),
    updateRuntime: vi.fn(),
    unarchiveHistorySession: vi.fn(),
    reactivateSession: vi.fn(),
  };
}
