-- plan model-wiring-and-handoff-20260514 Step 1.1：spawn 时 frontmatter `model` 透传给 SDK 后
-- 持久化到 sessions.model，让 SDK resume / dormant 唤醒后保持模型一致（与 permission_mode /
-- claude_code_sandbox / codex_sandbox 同款 per-session resilience 模式）。
--
-- 字段值：自由 string（claude SDK 接受 'opus' / 'sonnet' / 'haiku' alias，也接受具体 model id 如
-- 'claude-opus-4-7-thinking-max[1m]'）。NULL = 不指定，SDK 自己读 ANTHROPIC_MODEL env。
--
-- 兼容性：claude-code / codex-cli 双路径都持久化 + runtime 真生效。
-- claude-code:SDK options.model;codex-cli (codex-sdk v0.131.0+):ThreadOptions.model;
-- aider / generic-pty 等其他 adapter 持久化但不消费(adapter 自决)。
-- prompt-asset-review-optimize-20260527 修订:codex-sdk v0.131.0+ ThreadOptions.model 已支持
-- per-thread override(原迁移注释基于 codex-sdk 旧版判断"不接受"已过期),codex 端本字段对
-- runtime 真生效,fallback 链 ThreadOptions.model > ~/.codex/config.toml 顶层 model。
ALTER TABLE sessions ADD COLUMN model TEXT;
